### ISSUE TITLE
Running inference models on multiple CPUs ? 

### ISSUE THREAD

**Issue by lesommer** [alexis-barge/eophis#1]
Eophis allows to define python models that can be coupled to timestepping codes (as NEMO) through OASIS. But as present, the python runs on a single processor. 

Eophis should probably eventually allow to define python models that run on different processors. But it is not clear yet how Eophis should deal with inference on multiple CPUs. 

A a priori design requirement would be to keep the users-provided python code as agnostic as possible to the hardware constraints.

**Comment by alexis-barge** [comment]
Eophis_v1.0.0 has new features to run Python models on grid scattered over several processes with automatically reconstructed overlapping cells, allowing to use CNNs and differential calculus on partial subdomain. 

User only has to define global grid with number of desired halos and choose number of executing processes.

Successful [NEMO experiment](https://github.com/morays-community/NEMO-Subgrid_Density/tree/e221855b9a3287d4a218be3382b960e185af3215) with exchange of whole 3D grids for gradient-based model.
