### ISSUE TITLE
Does OASIS allow to couple codes running on GPUs and CPUs ? 

### ISSUE THREAD

**Issue by lesommer** [alexis-barge/eophis#2]

**Comment by alexis-barge** [comment]
OASIS does not run on GPUs and won't be updated to do so. Yet it is still possible to execute the coupled Python model on GPUs while OASIS communications and the geoscientific model are executed on CPUs. 
See more helping guidelines [here](https://morays-doc.readthedocs.io/en/latest/nemo.tools.html#hybrid-cpu-gpu-execution)
